### ISSUE TITLE
List of validators doesn't show the percentage of validated blocks

### ISSUE THREAD

**Issue by marcotradenet** [commercionetwork/almerico#104]
## Reference

https://testnet.commercio.network/validators/

## Observed behavior

The percentage of validated blocks does not appear and the list seems to continue to load something. The behavior seems to occur when there is a validator in the list that does not validate any blocks and for which the information cannot be retrieved.

On the page of the validator is displayed a continuous loading of information about the last 100 blocks

https://testnet.commercio.network/validators/detail/did:com:valoper10dlg49ptxr38a5r2mdgtcpdyxpst2hz48z73mp

**Comment by marcotradenet** [comment]
Now the problem is disappeared.     
Maybe it only happens in case the validator hasn't reached 100 validated blocks.

**Comment by zenit70** [comment]
@marcotradenet 
The error happens when a validator is in the list of validators with status `bonded`, but does not exist in the list of validatorsets at the same height

**Comment by marcotradenet** [comment]
> @marcotradenet
> The error happens when a validator is in the list of validators with status `bonded`, but does not exist in the list of validatorsets at the same height

Ok. The problem can be fixed in a short time?
