### ISSUE TITLE
Validator Detail - Delegator Amounts - pagination options

### ISSUE THREAD

**Issue by ErreVi** [commercionetwork/almerico#105]
It could be usefull to provide the same dropdown selection on the `item per pagination value`

Example 
https://testnet.commercio.network/validators/detail/did:com:valoper1ttxcnevaxlk58u4uuec2n7cm44rk9tsgmyj4hg

![Schermata 2022-03-02 alle 6 13 45 PM](https://user-images.githubusercontent.com/848884/156413310-a82d273a-0800-406c-a3b5-79aaf3e4c51a.png)

as present in `Account Detail`

Example 
https://testnet.commercio.network/account/did:com:1dv652j7562repkap9uvql3maj0l7qr64ek9wyh

![Schermata 2022-03-02 alle 6 14 37 PM](https://user-images.githubusercontent.com/848884/156413417-b8fed005-cb0d-412b-a5c4-18b10aa9f4fa.png)

**Comment by zenit70** [comment]
Implemented in version 3.0.5
