### ISSUE TITLE
Transactions without logs don't show in transactions list

### ISSUE THREAD

**Issue by marcotradenet** [commercionetwork/almerico#11]
If a transaction haven't logs doesn't show in transactions list in explorer dashboard    

https://testnet.commercio.network     

The transactions without logs don't show in transactions page also     

https://testnet.commercio.network/it/transactions     

Example of transaction without logs      

https://testnet.commercio.network/it/transaction/E248EB0AB7AFD78460040B0BA54A3BDD7F2BD7E2C40124DF6F47FEAFF463E0A8

**Comment by zenit70** [comment]
If there are no logs in a transaction we cannot know if it was successful or if it failed. 
We have to decide how to handle the case:
- do we use a default value?
- do we show an error message?
- ...?

**Comment by marcotradenet** [comment]
If element log doesn't exists consider transaction failed with unknown details.    
After that we will try use element `raw_log` for the details.
