### ISSUE TITLE
Update to cosmos sdk 0.38

### ISSUE THREAD

**Issue by marcotradenet** [commercionetwork/almerico#13]
It is necessary to check the compatibility of Almerico explorer with cosmos sdk version 0.38.

**Comment by zenit70** [comment]
@marcotradenet  Are the values of LCD, RPC and websocket always the same or do I have to configure the explorer with different parameters?

**Comment by zenit70** [comment]
@marcotradenet The new version of explorer has been released, I think this issuecan be closed.
