### ISSUE TITLE
Errore nel recuperare i dati

### ISSUE THREAD

**Issue by angeloderrico** [commercionetwork/almerico#14]
Buongiorno,
Sul link **https://testnet.commercio.network/it/validators**, selezionando il mio nodo validatore, ricevo il seguente messaggio:

**Errore nel recuperare i dati**

E' possibile comprendere il problema?

Grazie infinite.

Angelo D'Errico

**Comment by zenit70** [comment]
E' un problema con le API di Keybase per il recupero dell'immagine del validatore; se disabilito quella parte di codice torna a funzionare tutto correttamente, senza immagine ovviamente.

Grazie della segnalazione, con i prossimi aggiornamenti proviamo a risolvere.

Fulvio

**Comment by angeloderrico** [comment]
Grazie per la tua cortese risposta. Non si spiega però come, selezionando altri validatori, vedo i dettagli.

Hai qualche idea?

Grazie infinite.


Angelo D'Errico

**Comment by zenit70** [comment]
> Non si spiega però come, selezionando altri validatori, vedo i dettagli.

Se mi dici quali controllo.

In generale ho notato che si vedono solamente i dettagli dei validatori che non hanno l'immagine su Keybase, ma mostrano solamente il logo di default.

Fulvio

**Comment by angeloderrico** [comment]
Ad esempio, 'corvallis-test' ne vedo i dettagli, mentre per 'aderrico-test' no.

Vero quello che dici, occorre comprendere prima di poterne cambiare il loro.

Se mi dai dire qualcosa di più in merito, sicuramente sarà cosa gradita.


Angelo

**Comment by angeloderrico** [comment]
'2WS' anche ha lo stesso problema.


Angelo

**Comment by zenit70** [comment]
'corvallis-test' ha il logo di default.

Comunque ho commentato il codice che scarica l'immagine da Keybase ed adesso dovresti riuscire a vedere i dettagli del tuo validatore.

Poi quando capisco perché hanno smesso di funzionare le API di KeyBase ripristino l'immagine.

Fulvio

**Comment by angeloderrico** [comment]
Funziona perfettamente!
Grazie infinite per la cortesia, Fulvio.

Angelo
