### ISSUE TITLE
Some transactions do not appear in the list

### ISSUE THREAD

**Issue by marcotradenet** [commercionetwork/almerico#17]
Some transactions do not appear in the list. For example

https://testnet.commercio.network/it/transaction/352A46C5B9B710983F456753437DA88678D77FE286A2F0DD5DD806D5ADFF42CA

The detail is displayed but if I look in the list

https://testnet.commercio.network/it/transactions

the transaction doesn't appear.    
It is also not indicated in detail whether the transaction was successful.

**Comment by zenit70** [comment]
@marcotradenet 

The example transaction can be found at the 4355 height.
If you try to call this <https://lcd-testnet.commercio.network/txs?message.action=create_validator&tx.minheight=4354&tx.maxheight=4356>, the response is:

```js
{
    "total_count": "0",
    "count": "0",
    "page_number": "1",
    "page_total": "0",
    "limit": "30",
    "txs": []
}
```
If you try this <https://lcd-testnet.commercio.network/txs?tx.minheight=4354&tx.maxheight=4356>, the response is:

```js
{
    "total_count": "1",
    "count": "1",
    "page_number": "1",
    "page_total": "1",
    "limit": "30",
    "txs": [...]
}
```

This is why transactions with an error are not found. The search for a transaction takes place in the 'logs' property which when there is an error is not present. To fix this error is need to find a method to search for transactions that have failed.

In addition, the local transaction filter is also performed on the 'logs' property of the transactions, which would obviously have no effect on a failed transaction.

**Comment by zenit70** [comment]
@marcotradenet The transactions that fail are displayed with the new version of the explorer, I think that this issue can be closed.
