### ISSUE TITLE
Implement new transaction type MsgSetMembership

### ISSUE THREAD

**Issue by marcotradenet** [commercionetwork/almerico#19]
Implement the search and display of the transaction message `MsgSetMembership`.  

Structure of the transaction

```
MsgSetMembership {
       "government_address" <gov address>
       "subscriber <subscriber address>
       "new_membership" <membership associated>
}
```

`<membership associated>` could be one of these options

- green
- bronze
- silver
- gold
- black

**Comment by zenit70** [comment]
Fixed
