### ISSUE TITLE
Changing active account in Keplr doesn't refresh the wallet addres in Almerico

### ISSUE THREAD

**Issue by davide-perego-commercio** [commercionetwork/almerico#191]
Piccolo bug per Almerico: se cambio account (ne ho multipli in Keplr) l'indirizzo del wallet connesso mostrato in alto non si aggiorna in automatico. Va fatto refresh della pagina.

Small bug for Almerico: if I change the active account (I have many) in Keplr, the displayed address for connected wallet in the rectangle doesn't update automatically. I have refresh page.

**Comment by zenit70** [comment]
Rilasciata nuova versione `4.3.0` del'explorer che risolve l'aggiornamento in automatico dell'indirizzo del wallet connesso, grazie per la segnalazione.

Sono stati aggiornati anche i parametri della chain di `Commercio` suggerita a Keplr. Pertanto è necessario rimuovere dall'estensione di Keplr la chain salvata precedentemente e aggiungerla nuovamente.

Cordiali saluti

---

Released new version `4.3.0` of explorer that fixes automatic update of connected wallet address, thanks for the issue.

The parameters of the `Commercio` chain suggested to Keplr have also been updated. Therefore it is mandatory to remove from Keplr`s extension the previously saved chain and add it again.

Best regards
