### ISSUE TITLE
Implement membership visualization

### ISSUE THREAD

**Issue by marcotradenet** [commercionetwork/almerico#20]
In the account detail view 

`https://testnet.commercio.network/it/account/<did address>`

display the membership type on the right of the address with an icon of a card depending on the value. 
The icons must be those of font-awesome pro.  
To get the membership call the rest api 

`https://lcd-testnet.commercio.network/membership/<did address>`

The rest api returns the json

```json
{"height": "0", "result":{
  "user": "<did address>",
  "membership_type": "black"
}}
```

Extract `membership_type` that could be one of these values

- green
- bronze
- silver
- gold
- black

**Comment by zenit70** [comment]
@marcotradenet @enricotal70 

>The icons must be those of font-awesome pro.

I don't have this icons set at home.

**Comment by enricotal70** [comment]
[fontawesome-pro-5.13.0-web.zip](https://github.com/commercionetwork/almerico/files/4492982/fontawesome-pro-5.13.0-web.zip)

**Comment by zenit70** [comment]
@marcotradenet @enricotal70 

In my opinion it would be better to use the free icons, because Almerico already has them all provided by an installed package; moreover the project is open source and I don't know if it's allowed to use the paid icons.

**Comment by zenit70** [comment]
Implemented
