### ISSUE TITLE
Block hash error

### ISSUE THREAD

**Issue by marcotradenet** [Commercionetwork/Almerico#34]
It seems that the block hash is not correct: Almerico takes the value 
```json
"block": {
   "header": {
       ....
       "last_block_id": {
           "hash": "E38F27781B1E45DC11C49D6E1FBA7F3AC590877E9D2FFF84D1BB48A2F4938240", 
....
```
While it should take the value 
```json
  "block_id": {
    "hash": "5D6F1E291F832BF5D02BC31F8742EA663D14BF813B532AE6916160236EEF8345", 
```
Other explorers like Mintscan or Bigdipper take that value

**Comment by zenit70** [comment]
Will be fixed in the next version of Almerico

**Comment by zenit70** [comment]
@marcotradenet 

I cannot find this property 

```json
"block_id": {
    "hash": "5D6F1E291F832BF5D02BC31F8742EA663D14BF813B532AE6916160236EEF8345", 
```

in the structure of the block json.

Do you mean this property?

```json
"last_commit": {
  "block_id": {
      "hash": "5D6F1E291F832BF5D02BC31F8742EA663D14BF813B532AE6916160236EEF8345", 
  }
}

I enclose a sample json of the block:
[block.zip](https://github.com/commercionetwork/almerico/files/5842843/block.zip)


```

**Comment by marcotradenet** [comment]
I used this endpoint of lcd

```
https://lcd-testnet.commercio.network/blocks/467628
```

The response json contains `block_id` element.      
I don't know what endpoint you are using.

**Comment by zenit70** [comment]
Unfortunately, the 'new block' event issued by the websocket only contains the second part of the json structure, the one I attached in the previous message.

So the hash value you would like to display may possibly be displayed in the detail view, not in the list of blocks that is continuously populated by the events issued by the websocket.

**Comment by marcotradenet** [comment]
But the right hash value of block 467628 should be `9A8D662283A1142E63C17C75A0C3A68C6E85EB2C6F2D4F2117861294D808C943`. I don't know if  'new block' event contains the right value.     
Alternatively couldn't you take the height of the block and call directly the api `/blocks/<HEIGH_FROM_EVENT>`?

**Comment by zenit70** [comment]
>I don't know if 'new block' event contains the right value.

The event json: [event.zip](https://github.com/commercionetwork/almerico/files/5847520/event.zip)

>Alternatively couldn't you take the height of the block and call directly the api /blocks/<HEIGH_FROM_EVENT>?

Yes, i can after the event has be emitted.

If the hash to be displayed is the one within the 'block_id' property, it is necessary to update all code that uses the block data as it will be nested one level further. Currently, only the data within the block property is used.
The change, therefore, is more complex than just updating the displayed value.

[block.zip](https://github.com/commercionetwork/almerico/files/5847547/block.zip)
