### ISSUE TITLE
Errore conteggio ucommercio

### ISSUE THREAD

**Issue by NicolaContin** [commercionetwork/almerico#39]
Buongiorno, sia sulla pagina dei validatori

https://mainnet.commercio.network/validators/validator/did:com:valoper1rsyglnhpg7q6hvz3422wm63tehtkx5xaflh8up

che sui singoli indirizzi
https://mainnet.commercio.network/validators/account/did:com:1rkrnz57sf0474m6pyx453aghcyxpra3spm5sdg

Tutti i valori degli ucommercio risultano errati 

Ad esempio, sul validatore del link in alto, non sono stati delegati 212.121.212.121 ucommercio, ma bensì 220.000.000.000 ucommercio

Esempio di schermate

<img width="1314" alt="Schermata 2021-03-24 alle 09 46 13" src="https://user-images.githubusercontent.com/26112814/112281100-fa21f300-8c85-11eb-8056-3065146eaa07.png">
<img width="1314" alt="Schermata 2021-03-24 alle 09 47 01" src="https://user-images.githubusercontent.com/26112814/112281111-fbebb680-8c85-11eb-8815-9b7252969bd8.png">

**Comment by zenit70** [comment]
Buongiono @NicolaContin ,

mi servono ulteriori informazioni riguardo questa segnalazione riportata nell'immagine relativa ai dettagli dell'account:

![immagine](https://user-images.githubusercontent.com/19747789/112327707-f4dc9c80-8cb5-11eb-9f2a-cf72187c99c5.png)

1. Perché ritiene questo valore un errore? 
2. Qual è il valore che si apetterebbe fosse visualizzato?

Grazie

Fulvio

**Comment by NicolaContin** [comment]
No, mi sono sbagliato su balance non dovrebbe esserci alcun errore, ho visto che sono cambiate le unità di misura, solo che adesso sono spariti i reward

<img width="1336" alt="Schermata 2021-03-25 alle 17 16 15" src="https://user-images.githubusercontent.com/26112814/112506305-e82b7780-8d8d-11eb-8233-31e281eee510.png">

**Comment by zenit70** [comment]
Buongiorno @NicolaContin,

>solo che adesso sono spariti i reward,

Riguardo al fatto che sia stato notato un basso tasso di ricompense, abbiamo modificato l'algoritmo e cambiato i parametri della chain. Stiamo verificando se il tasso di distribuzione corrisponde a quanto atteso, ed eventualmente lo correggeremo nei prossimi giorni.
La correzione non comporterà nessuna procedura di aggiornamento da parte dei nodi validatori.
Per quanto riguarda le ricompense prima presenti nei singoli account derivanti dall'attività dei nodi validatori su cui erano state fatte le deleghe, questi ultimi sono stati distribuiti al momento dell'aggiornamento.

>se possibile sarebbe da uniformare con la stessa unità di misura anche Balance, magari usando più cifre dopo la virgola se servono

Nei prossimi rilasci l'unità di misura sarà uniformata alla altre, per quello che rigurarda il numero di decimali valutiamo la richiesta.

**Comment by NicolaContin** [comment]
Buongiorno, forse mi sono spiegato male, grazie per la precisazione sui tassi delle ricompense, ma intendevo che la somma delle ricompense prese precedentemente non sono più visibili, questo account ha tenuto in stake 50k per 6 mesi e i circa 2k di token guadagnati, non sono più visibili, infatti sulla capitalization totale non si vede

**Comment by zenit70** [comment]
Buongiorno, l’account appunto ha 2.747 token (visualizzato in basso a sinistra nella pagina dell’account), i quali possono essere messi in stake nuovamente sul validatore. Come già spiegato le ricompense sono state distribuite automaticamente durante l’upgrade.

Inoltre anche l’account che ha creato il validatore ha ricevuto ricompense, come visualizzato nella relativa schermata <https://mainnet.commercio.network/validators/account/did:com:1k78p5gvga70urv2ts33h4vcykyhpatqywnwpj8>, e anche quest’ultimo può delegare nuovamente al validatore

**Comment by NicolaContin** [comment]
Si mi è chiaro, correggimi se sbaglio, ma quei 2.747 token distribuiti, dovrebbero risultare sul Total della scheda Capitalization, che dovrebbe passare da 50.001,54 a 52.748,decimali, giusto?

Grazie
NC

**Comment by zenit70** [comment]
Il motivo per cui i valori della tabella `Balance` sono gestiti separatamente dalla tabella Capitalization e che questa scheda visualizza valori espressi in `ucommercio`, ma anche in `ucc` e tutti quelli che possono o potranno essere presenti:
![image](https://user-images.githubusercontent.com/19747789/112618725-bd413200-8e26-11eb-9395-6c6a6fe52441.png)

La tabella `Capitalization` invece visualizza esclusivamente valori espressi in `ucommercio` a cui non è corretto sommare `uccc` o altro.

**Comment by NicolaContin** [comment]
Perfetto, allora come feedback e non come bug suggerisco di inserire nella scheda Capitalization il totale dei soli COM presenti nell'account, che siano stati ricevuti da VBR o da altro, in modo che il totale dei commercio token che uno possiede sia preciso con la reale somma dei token. Inoltre a parità di valuta, dovrebbe esserci la stessa unità di misura per rendere più comprensibile la scheda

Grazie e buon lavoro
NC
