### ISSUE TITLE
Add variable for api version

### ISSUE THREAD

**Issue by marcotradenet** [commercionetwork/almerico#9]
Add `VUE_APP_API_VERSION` variable to recognize version of cosmos sdk api.
At docker build use
```
docker build -t almerico \
  --build-arg LCD_URL=<LCD URL> \
  --build-arg RPC_URL_rpc=<RPC URL> \
  --build-arg WS_URL=<WebSocket URL> \
  --build-arg API_VERSION=<Sdk Api version> \
  .
```

**Comment by zenit70** [comment]
@marcotradenet 

Are the versions we support '0.36' and '0.38'?

We could also use the 'config' file to set the API version; however, in my opinion, the most correct place to set the version is an environment variable.

**Comment by marcotradenet** [comment]
```
Are the versions we support '0.36' and '0.38'?
```
Yes, only 0.36 and 0.38 for now. Default 0.36.
```
We could also use the 'config' file to set the API version; however, in my opinion, the most correct place to set the version is an environment variable.
```
Handle only as environment variable
